---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-secured-header@kubernetescrd
    traefik.ingress.kubernetes.io/router.tls: "true"
  labels:
    app.kubernetes.io/name: sample-ingress
    app.kubernetes.io/instance: sample-ingress
    app.kubernetes.io/component: ingress
  name: sample-ingress
  namespace: default
spec:
  ingressClassName: traefik
  rules:
    - host: localhost
      http:
        paths:
          - backend:
              service:
                name: sample-service
                port:
                  number: 8080
            path: /
            pathType: Prefix
  # tls:
  #   {{ create_ingress_spec_tls | indent( width=4) }}
