---

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: beta
resources:
  - ../../base
nameSuffix: -beta
labels:
  - pairs:
      env: beta
      app.kubernetes.io/name: beta-ingress
      app.kubernetes.io/instance: beta-ingress
      app.kubernetes.io/component: ingress
    includeSelectors: false
patches:
  - path: beta-ingress.yaml
    target:
      kind: Ingress
      name: sample-ingress
